name: "IFILE Project CI/CD"
on:
  push:
    branches: [ master ]
  pull_request:
    branchs: [ master ]
jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb+srv://localhost/file
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use MongoDB from Github actions
        uses: supercharge/mongodb-github-action@1.9.0
      - run: npm install